version: "3.8"

services:
  forge-minecraft-server:
    image: ghcr.io/dsxack/forge-minecraft-server:master
    container_name: forge-minecraft-server
    ports:
      - "25555:25555"
    volumes:
      - "./mods:/opt/minecraft/mods"
      - "./world:/opt/minecraft/world"
      - "./server.properties:/opt/minecraft/server.properties"
    restart: always
    pull_policy: always
